name: Runer 2Trim 
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push]
jobs:
  Mi-Primer-Ubuntu:
    runs-on: self-hosted
    steps:
      - name: Download the microservice Repository
        run: |
          rm -rf microservicio || true
          git clone https://github.com/pps-ciberseguridad/microservicio.git microservicio
          cd microservicio
          docker build -t myapp:1.0 .
      - name: Scan microservice repositorie code with Sonarqube
        uses: sonarsource/sonarqube-scan-action@master
        with:
          projectBaseDir: ./microservicio/
          args: >
            -Dsonar.projectKey=jjmorae
        env:
          SONAR_TOKEN: ${{ secrets.SONARQUBE_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONARQUBE_HOST }}
      - name: Logging to registry
        uses: docker/login-action@v3
        with:
          registry: https://registry.pedroclemente.cloud:9443/
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: microservicio
          push: true
          tags: registry.pedroclemente.cloud:9443/microservicio-${{ github.actor }}-exam2t:1.0
      - name: Run trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: registry.pedroclemente.cloud:9443/microservicio-${{ github.actor }}-exam2t:1.0
          format: 'sarif'
          exit-code: '0'
          output: 'trivy-results.sarif'
         

